version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8000"
    volumes:
      - ./app:/app
    environment:
      - DEBUG=1
    restart: unless-stopped
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: myroslav_db
      POSTGRES_USER: myroslav_user
      POSTGRES_PASSWORD: myroslav_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres_data:
